# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dims', models.CharField(max_length=50)),
                ('stackable', models.BooleanField()),
                ('tiltable', models.BooleanField()),
                ('image_front', models.ImageField(upload_to='')),
                ('image_top', models.ImageField(upload_to='')),
            ],
        ),
    ]
