# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='stackable',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='tiltable',
            field=models.NullBooleanField(),
        ),
    ]
